import type { Metadata } from 'next'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'

export const metadata: Metadata = {
  title: 'Terms of Service — YChecker',
  description: 'Terms and conditions for using YChecker.',
}

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="flex-1">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <h1
            className="text-2xl font-bold mb-6"
            style={{ color: '#111111' }}
          >
            Terms of Service
          </h1>
          <p className="text-xs mb-8" style={{ color: '#AAAAAA' }}>
            Last updated: July 2026
          </p>

          <div className="space-y-6 text-sm leading-relaxed" style={{ color: '#333333' }}>
            <section>
              <h2 className="text-base font-semibold mb-2" style={{ color: '#111111' }}>
                1. Service Description
              </h2>
              <p>
                YChecker is an AI-powered evaluation tool for Y Combinator (YC)
                startup applications. We provide automated feedback, scoring,
                and rewrite suggestions based on publicly known YC evaluation
                criteria. YChecker is <strong>not affiliated with</strong>,
                endorsed by, or connected to Y Combinator in any way.
              </p>
            </section>

            <section>
              <h2 className="text-base font-semibold mb-2" style={{ color: '#111111' }}>
                2. No Guarantee of Acceptance
              </h2>
              <p>
                YChecker&apos;s evaluations are for informational purposes only.
                A high score on YChecker does <strong>not guarantee</strong>{' '}
                acceptance into Y Combinator. A low score does not mean you will
                be rejected. YC&apos;s admission process considers many factors
                beyond what can be evaluated through application text alone.
              </p>
            </section>

            <section>
              <h2 className="text-base font-semibold mb-2" style={{ color: '#111111' }}>
                3. User Accounts
              </h2>
              <ul className="list-disc pl-5 space-y-1">
                <li>You must provide a valid email address to create an account.</li>
                <li>You are responsible for maintaining the security of your account.</li>
                <li>You may delete your account and all data at any time from the Account page.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-base font-semibold mb-2" style={{ color: '#111111' }}>
                4. Payments & Refunds
              </h2>
              <p>
                All payments are processed securely through Razorpay. Prices are
                displayed in INR. Once a report has been generated and
                delivered, <strong>no refunds</strong> will be issued, as the
                service has been fully rendered. If you experience a technical
                issue preventing report delivery, contact us for assistance.
              </p>
            </section>

            <section>
              <h2 className="text-base font-semibold mb-2" style={{ color: '#111111' }}>
                5. Intellectual Property
              </h2>
              <p>
                You retain full ownership of the application content you
                submit. The evaluation reports generated by YChecker are
                licensed to you for personal use. You may not resell or
                redistribute reports generated for other users.
              </p>
            </section>

            <section>
              <h2 className="text-base font-semibold mb-2" style={{ color: '#111111' }}>
                6. Usage Limits
              </h2>
              <p>
                To prevent abuse, accounts are limited to 3 application
                submissions per hour. Automated or scripted submissions are
                prohibited.
              </p>
            </section>

            <section>
              <h2 className="text-base font-semibold mb-2" style={{ color: '#111111' }}>
                7. Limitation of Liability
              </h2>
              <p>
                YChecker is provided &ldquo;as is&rdquo; without warranties of
                any kind. We are not liable for any decisions you make based on
                our evaluations, including decisions to submit or not submit a
                YC application.
              </p>
            </section>

            <section>
              <h2 className="text-base font-semibold mb-2" style={{ color: '#111111' }}>
                8. Changes to Terms
              </h2>
              <p>
                We may update these terms from time to time. Continued use of
                the service after changes constitutes acceptance of the updated
                terms.
              </p>
            </section>

            <section>
              <h2 className="text-base font-semibold mb-2" style={{ color: '#111111' }}>
                9. Contact
              </h2>
              <p>
                For questions about these terms, contact us at{' '}
                <a
                  href="mailto:kushagraceo17@gmail.com"
                  style={{ color: '#FF6B35' }}
                >
                  kushagraceo17@gmail.com
                </a>
                .
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}
